[build]
  command = "git submodule update --init --recursive && npm run build"
  publish = "dist"

# Astro generates static files, no SPA redirects needed
# Let Astro handle 404s naturally

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
